"""
Constants for the Team Project Planner application.
"""

import os

# Database paths
DB_DIR = "db"
USERS_DB_PATH = os.path.join(DB_DIR, "users.json")
TEAMS_DB_PATH = os.path.join(DB_DIR, "teams.json")
BOARDS_DB_PATH = os.path.join(DB_DIR, "boards.json")
TASKS_DB_PATH = os.path.join(DB_DIR, "tasks.json")

# Export paths
EXPORT_DIR = "out"

# Validation constraints
MAX_NAME_LENGTH = 64
MAX_DESCRIPTION_LENGTH = 128
MAX_DISPLAY_NAME_LENGTH = 64
MAX_DISPLAY_NAME_UPDATE_LENGTH = 128
MAX_TEAM_MEMBERS = 50

# Status constants
BOARD_STATUS_OPEN = "OPEN"
BOARD_STATUS_CLOSED = "CLOSED"

TASK_STATUS_OPEN = "OPEN"
TASK_STATUS_IN_PROGRESS = "IN_PROGRESS"
TASK_STATUS_COMPLETE = "COMPLETE"

VALID_TASK_STATUSES = [TASK_STATUS_OPEN, TASK_STATUS_IN_PROGRESS, TASK_STATUS_COMPLETE]
VALID_BOARD_STATUSES = [BOARD_STATUS_OPEN, BOARD_STATUS_CLOSED]

# HTTP Status codes
HTTP_OK = 200
HTTP_CREATED = 201
HTTP_BAD_REQUEST = 400
HTTP_NOT_FOUND = 404
HTTP_INTERNAL_SERVER_ERROR = 500
